##### BEGIN modeco/Dockerfile/image-header #####
FROM vcwebio/conteco.image.wrapper AS base
##### END modeco/Dockerfile/image-header #####

##### BEGIN image/Dockerfile/conteco #####
COPY ./conteco/ /conteco/
RUN chmod -R +x /conteco/bin && rm -rf /conteco/repo
COPY ./ /conteco/repo/
##### END image/Dockerfile/conteco #####

##### BEGIN image/Dockerfile/build-instructions #####
ENV CONTECO_ENTRYPOINT "/entrypoint-artifactory.sh"
##### END image/Dockerfile/build-instructions #####

##### BEGIN image.base/Dockerfile/env-labels-footer #####
ENV CONTECO_REALM="vcwebio" \
    CONTECO_ECOSYSTEM="modeco" \
    CONTECO_TYPE="backup" \
    CONTECO_NAME="module" \
    CONTECO_TAG="20200504" \
    CONTECO_BASE="image.wrapper" \
    CONTECO_BUILD="modeco"
LABEL io.vcweb.schema-version="1.0" \
      io.vcweb.realm="vcwebio" \
      io.vcweb.ecosystem="modeco" \
      io.vcweb.type="backup" \
      io.vcweb.name="module" \
      io.vcweb.tag="20200504" \
      io.vcweb.base="image.wrapper" \
      io.vcweb.build="modeco" \
      io.vcweb.label="backup.module - Modeco" \
      io.vcweb.description="Backup of all repositories of the module images of the ModEco ecosystem." \
      io.vcweb.docker.cmd.help="docker run vcwebio/modeco.backup.module --help"
##### END image.base/Dockerfile/env-labels-footer #####
